# adapted from the conda-forge thinc recipe
{% set name = "thinc" %}
{% set version = "8.0.2" %}
{% set sha256sum = "20f033b3d9fbd02389d8f828cebcd3a42aee3e17ed4c2d56c6d5163af83a9cee" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  patches: 
    - 0100-importorskip-tests.patch

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip {{ pip }}
    - numpy {{ numpy }} 
    - python {{ python }}
    - cython {{ cython }}
    - setuptools {{ setuptools }}
    - wheel {{ wheel }} 
    - murmurhash {{ murmurhash }}
    - cymem {{ cymem }}
    - preshed {{ preshed }}
    - cython-blis {{ cython_blis }}

  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - murmurhash {{ murmurhash }}
    - cymem {{ cymem }} 
    - preshed {{ preshed }}
    - cython-blis {{ cython_blis }}
    - srsly {{ srsly }}
    - wasabi {{ wasabi }}
    - tqdm {{ tqdm }}
    - catalogue {{ catalogue }}
    - pydantic
    - dataclasses                                   # [py36]    
    - typing_extensions {{ typing_extensions }}     # [py<38] 
    - contextvars  # [py36]

test:
  requires:
    - hypothesis <=5.0.0
    - pytest
    - mock
    - pathy

  imports:
    - thinc
    - thinc.api
    - thinc.linear
    - thinc.extra
    - thinc.neural

  commands:
    - python -m pytest --tb=native --pyargs {{ name }}

about:
  home: https://github.com/explosion/thinc/
  license: MIT
  license_family: MIT  
  license_file: LICENSE
  summary: 'thinc: Learn super-sparse multi-class models'
  description: |
    thinc is a Cython library for learning models with millions of parameters
    and dozens of classes. It drives https://spacy.io , a pipeline of very
    efficient NLP components. I’ve only used thinc from Cython; no real Python
    API is currently available.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
