# adapted from the conda-forge thinc recipe
{% set name = "thinc" %}
{% set version = "8.0.3" %}
{% set sha256sum = "c370a7a46d01b588d8d5f99d8d5e36b3cbac4512638356fa430f7f52bb3a8897" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  patches: 
    - 0100-importorskip-tests.patch

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  ignore_run_exports:
    - libgcc-ng
    - libstdcxx-ng

requirements:
  build:
    - {{ compiler('cxx') }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  host:
    - pip {{ pip }}
    - numpy {{ numpy }} 
    - python {{ python }}
    - cython {{ cython }}
    - setuptools {{ setuptools }}
    - wheel {{ wheel }} 
    - murmurhash {{ murmurhash }}
    - cymem {{ cymem }}
    - preshed {{ preshed }}
    - cython-blis {{ cython_blis }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}

  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - murmurhash {{ murmurhash }}
    - cymem {{ cymem }} 
    - preshed {{ preshed }}
    - cython-blis {{ cython_blis }}
    - srsly {{ srsly }}
    - wasabi {{ wasabi }}
    - catalogue {{ catalogue }}
    - pydantic {{ pydantic }}
    - dataclasses  {{ dataclasses }}                # [py36]
    - typing_extensions {{ typing_extensions }}     # [py<38]
    - contextvars                                   # [py36]

    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
test:
  requires:
    - hypothesis
    - importlib_metadata ==2.0.0
    - pytest
    - mock
    - pathy

  imports:
    - thinc
    - thinc.api
    - thinc.linear
    - thinc.extra
    - thinc.neural

  commands:
    - python -m pytest --tb=native --pyargs {{ name }}

about:
  home: https://github.com/explosion/thinc/
  license: MIT
  license_family: MIT  
  license_file: LICENSE
  summary: 'thinc: Learn super-sparse multi-class models'
  description: |
    thinc is a Cython library for learning models with millions of parameters
    and dozens of classes. It drives https://spacy.io , a pipeline of very
    efficient NLP components. I’ve only used thinc from Cython; no real Python
    API is currently available.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
