# adapted from the conda-forge thinc recipe
{% set name = "thinc" %}
{% set version = "8.0.8" %}
{% set sha256sum = "cf2abbd99c56f21b8804f31f995460515d95a5c5988be39e0964469e0070987b" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip {{ pip }}
    - numpy {{ numpy }} 
    - python {{ python }}
    - cython {{ cython }}
    - setuptools {{ setuptools }}
    - wheel {{ wheel }} 
    - murmurhash {{ murmurhash }}
    - cymem {{ cymem }}
    - preshed {{ preshed }}
    - cython-blis {{ cython_blis }}

  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - murmurhash {{ murmurhash }}
    - cymem {{ cymem }} 
    - preshed {{ preshed }}
    - cython-blis {{ cython_blis }}
    - srsly {{ srsly }}
    - wasabi {{ wasabi }}
    - catalogue {{ catalogue }}
    - pydantic {{ pydantic }}
    - dataclasses  {{ dataclasses }}                # [py36]
    - typing_extensions {{ typing_extensions }}     # [py<38]
    - contextvars                                   # [py36]

test:
  requires:
    - hypothesis
    - pytest
    - mock
    - pathy
    - numpy
    - srsly
    - typed-ast
    - pyzmq

  imports:
    - thinc
    - thinc.api
    - thinc.extra

  commands:
    - pip install mypy nbformat ml_datasets nbconvert
    - python -m pytest --tb=native --pyargs {{ name }} -k 'not test_mypy_results'

about:
  home: https://github.com/explosion/thinc/
  license: MIT
  license_family: MIT  
  license_file: LICENSE
  summary: 'thinc: Learn super-sparse multi-class models'
  description: |
    thinc is a Cython library for learning models with millions of parameters
    and dozens of classes. It drives https://spacy.io , a pipeline of very
    efficient NLP components. I’ve only used thinc from Cython; no real Python
    API is currently available.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
