# adapted from the conda-forge thinc recipe
{% set name = "thinc" %}
{% set version = "7.1.1" %}
{% set sha256sum = "68478efee64a5523d881d47914a92e315bb31bf0a404cec1ff7be83b0a267f3e" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - pip {{ pip }}
    - {{ compiler('cxx') }}
  host:
    - pip {{ pip }}
    - numpy {{ numpy }} 
    - python {{ python }}
    - setuptools {{ setuptools }}
    - wheel {{ wheel }} 

  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - murmurhash {{ murmurhash }}
    - cymem {{ cymem }} 
    - preshed {{ preshed }}
    - cython-blis {{ cython_blis }}
    - srsly {{ srsly }}
    - wasabi {{ wasabi }}
    - plac {{ plac }}
    - tqdm {{ tqdm }}

test:
  requires:
    - hypothesis <=5.0.0
    - pytest
    - mock

  imports:
    - thinc
    - thinc.api
    - thinc.linear
    - thinc.extra
    - thinc.neural

  commands:
    - python -m pytest --tb=native --pyargs {{ name }}

about:
  home: https://github.com/explosion/thinc/
  license: MIT
  license_file: LICENSE
  summary: 'thinc: Learn super-sparse multi-class models'
  description: |
    thinc is a Cython library for learning models with millions of parameters
    and dozens of classes. It drives https://spacy.io , a pipeline of very
    efficient NLP components. I’ve only used thinc from Cython; no real Python
    API is currently available.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
